services:

  commands:
    build:
      dockerfile: Dockerfile
    env_file: ./.env
  recommendation:
    build: .
    ports:
      - 3000:3000
    env_file: ./.env
    networks:
      - node-webapp-network
networks:
  node-webapp-network:
    driver: bridge
