Resources:
  FoodRecommendation:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: food-recommendation
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
